version: "3.7"

services:
  backend:
    container_name: myapp_backend
    restart: always
    build: .
    environment:
      - APP_ENV=development
      - APP_PORT=3000
    volumes:
      - ./src:/src
      - ./test:/test
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  mysql: # Example Service
    container_name: myapp_mysql
    restart: always
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=myapp
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=cruddocker
    ports:
    - "3306:3306"
    volumes:
    - myapp_mysql_data:/var/lib/mysql
  redis: # Example Service
    container_name: myapp_redis
    restart: always
    image: redis:6.0-alpine
    expose:
      - "6379"
    volumes:
      - myapp_redis_data:/data

volumes:
  myapp_mysql_data:
  myapp_redis_data:

networks:
  default:
    

      name: myapp